name: E2E on Chrome
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cypress run
        uses: cypress-io/github-action@v1
        with:
          browser: chrome
          start: npm run start:nobrowser
          # quote the url to be safe against YML parsing surprises
          wait-on: 'http://localhost:3000'
